### ISSUE TITLE
RequestContext cannot be accessed inside middleware

### ISSUE THREAD

**Issue by Langstra** [mikro-orm/nestjs#1]
|When accessing the RequestContext inside a controller like `RequestContext.currentRequestContext()` you get an Object and it is even possible to add new properties to it. However, inside nestjs middleware you get 'undefined' instead of an Object.

**Stack trace**
```
console.log
    undefined

      at ContextMiddleware.use (../src/context.middleware.ts:8:13)
```

**To Reproduce**
1. `git clone https://github.com/RiskChallenger/mikro-orm-issue`
2. `yarn`
3. `yarn start:dev`

**Expected behavior**
Expected to get the RequestContext inside the middleware instead of undefined

**Versions**

| Dependency | Version |
| - | - |
| mikro-orm | 4.0.0-alpha.12 |
| mikro-orm/nestjs | 4.0.0-alpha.1 |
| node | 14.4.0 |
| knex | 0.21.2 |
| mysql | 2 2.1.0 |
| typescript | 3.9.7 |

**Comment by B4nan** [comment]
That is because you are trying to read it before it gets created. Nothing I can do about this from the perspective of this package - the order is set by nest (or actually your code that defines the modules). 

You could probably create a submodule that would be imported after the `MikroOrmModule`, and register the middleware there. Another way would be to register the `RequestContext` manually - but that will need slight change in the code, so the context is not created if it already exists.

**Comment by B4nan** [comment]
In `4.0.0-alpha.2` you can disable automatic context middleware creation via `registerRequestContext: false` in the `forRoot()` method.
