### ISSUE TITLE
Injectable EventSubscribers

### ISSUE THREAD

**Issue by Davide-Gheri** [mikro-orm/nestjs#14]
**Is your feature request related to a problem? Please describe.**
It would be awesome if EventSubscriber classes could support NestJs DI so we can inject dependencies in them.

**Describe the solution you'd like**
The current `@Subscriber()` decorator cannot be used as it directly creates a new instance:
https://github.com/mikro-orm/mikro-orm/blob/master/packages/core/src/decorators/Subscriber.ts#L8
And I didn't find a clear solution to remove the attached subscriber before MikroORM init.

I think the easiest way is to have a new decorator (could be `@InjectableSubscriber()`, that also wraps Nestjs `@Injectable()` ?) that simply adds a metadata to the class prototype flagging it as a `Subscriber`, then the class has to be registered as a `provider` inside a Module (like any nestjs providers).

Then follow a common Nestjs pattern, "disover" this providers via the custom metadata and do stuff with them, in our case 
register them as subscriber (`em.getEventManager().registerSubscriber()`).

**Additional context**
As a reference, `@nestjs/bull` does the same for registering queue processors https://github.com/nestjs/bull/blob/master/lib/bull.explorer.ts .
It is a bit more complicated since it has to check every class methods instead of just the class, what we need are just the first lines of `explore()`:
```
const providers: InstanceWrapper[] = this.discoveryService
      .getProviders()
      .filter((wrapper: InstanceWrapper) =>
        this.metadataAccessor.isQueueComponent(wrapper.metatype),
      );
```
Replace `isQueueComponent` with something like `isSubscriberComponent` and voilà, we have an array of all provided subscribers.

**Comment by B4nan** [comment]
This is already possible:

```ts
@Injectable()
export class MySubscriber {

  constructor(em: EntityManager) {
    em.getEventManager().registerSubscriber(this);
  }

}
```

**Comment by EricMcRay** [comment]
> This is already possible:
> 
> ```ts
> @Injectable()
> export class MySubscriber {
> 
>   constructor(em: EntityManager) {
>     em.getEventManager().registerSubscriber(this);
>   }
> 
> }
> ```

Can you also put this to documents? I was looking for this solution for hours.

**Comment by henrytran9704** [comment]
Me to man :((

**Comment by B4nan** [comment]
What about sending a PR adding it to the docs yourself? :] 

This is open source, I cant do everything myself, especially not here, this nestjs adapter is something I never wanted to maintain myself, I just took over because the original maintainer stopped responding.

**Comment by hungtcs** [comment]
> This is already possible:
> 
> ```ts
> @Injectable()
> export class MySubscriber {
> 
>   constructor(em: EntityManager) {
>     em.getEventManager().registerSubscriber(this);
>   }
> 
> }
> ```

Do I need to do anything else?
Hooks doesn't work in my project, but `constructor` and `getsubscribedentities` was called.

**Comment by viweei** [comment]
Why can I only get em and typesense in the constructor? It is undefined in the afterCreate method.

```ts
@Subscriber()
@Injectable()
export class UserSubscriber implements EventSubscriber<User> {
  constructor(
    @Inject('TYPESENSE')
    private readonly typesense: Client,
    private readonly em: EntityManager,
  ) {
    console.log('1=', this.typesense, this.em);
  }

  getSubscribedEntities(): EntityName<User>[] {
    return [User];
  }

  async afterCreate(args: EventArgs<User>): Promise<void> {
    console.log('2=', this.typesense, this.em);
  }
}
```

here is log's output 

```log
[Nest] 14621  - 08/02/2022, 6:10:16 PM     LOG [MikroORM] [query] begin
[Nest] 14621  - 08/02/2022, 6:10:20 PM     LOG [MikroORM] [query] insert into `user` (`account`, `create_at`, `id`, `nickname`, `password`) values ('vi-7', '2022-08-02 18:10:16.911', 'cl6c0rhsf0000a5tn9tos7d4i', 'viweeix', '123456') [took 18 ms]
2= undefined undefined
[Nest] 14621  - 08/02/2022, 6:10:20 PM     LOG [MikroORM] [query] commit
```

**Comment by B4nan** [comment]
You need to register the subscriber in your constructor, otherwise the ORM will create new instance of it, hence no constructor parameters from nestjs DI.

https://github.com/mikro-orm/nestjs/issues/14#issuecomment-765245844

**Comment by tobiaskraus** [comment]
I tried many combinations. Including:

from comment [#14 (comment)](https://github.com/mikro-orm/nestjs/issues/14#issuecomment-765245844)

```ts
@Injectable()
export class ActivityLogSubscriber implements EventSubscriber<Building>{

  constructor(private readonly em: EntityManager) {
    em.getEventManager().registerSubscriber(this);
  }
}
```

app.module.ts

```ts
 @Module({
    imports: [
        MikroOrmModule.forRoot(),
        ...
    ],
    providers: [ActivityLogSubscriber],
```

### Problem: DependencyInjection for EntityManager in Subscriber not working

The `this.em` seems to be not the same as in my BuildingController. Because when I persist without flush in `beforeCreate` then it doesn't flush the changes later together with the building create changes (which calls flush inside BuildingService which uses em via DI). Here my Subscriber code:

```ts
    async beforeCreate(args: EventArgs<Building>): Promise<void> {
        console.log("beforeCreate called"); // gets called
        const log = this.em.create(ActivityLog, {
            // changes which never gets flushed
        });
        await this.em.persist(log);
    }
```

When i use `persistAndFlush` on a em fork, then it works, but I don't want to flush before the main building-create-changes.

## Other failed combinations

- Using not only `@Injectable` but also `@Subscriber`
  - caused error when I use it with the constructor code: `Cannot read properties of undefined (reading 'getEventManager'): em.getEventManager()`
- using `args.em` instead of `this.em`
  - didn't solve the problem
- no constructor and using `args.em`
  - same issue: persist without flush didn't flush the changes later on in the service' flush call -> not same em instance
- persistAndFlush on `args.em` or `this.em` (not on `em.fork()`)
  - caused `ValidationError: You cannot call em.flush() from inside lifecycle hook handlers`

**Comment by B4nan** [comment]
> The this.em seems to be not the same as in my BuildingController.

It is the same global instance, but it works differently based on the async context. 

https://mikro-orm.io/docs/identity-map#how-does-requestcontext-helper-work

> Because when I persist without flush in beforeCreate then it doesn't flush the changes later together with the building create changes (which calls flush inside BuildingService which uses em via DI). 

You can't persist things from inside `beforeCreate` event, that is too late, changesets are already computed. You need `onFlush` event. 

https://mikro-orm.io/docs/events#using-onflush-event

Also note that `persist` is a sync method, you are not flushing anything in your code. 

Your issue is not about nest DI at all, this would work the same with a lifecycle hook too, and is expected behaviour.
